### ISSUE TITLE
Logger crashes robot

### ISSUE THREAD

**Issue by randomtestfive** [RAR1741/RA18_RobotCode#56]
```
********** Robot program starting **********
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'log4j2.debug' to show Log4j
2 internal initialization logging.
Error at java.net.URLClassLoader$1.run(URLClassLoader.java:372): Unhandled exception instantiating robot org.redalert1741.powerup.Robot java.lang.ClassNotFoundException
: java.beans.PropertyChangeEvent
        at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.apache.logging.log4j.core.LoggerContext.updateLoggers(LoggerContext.java:654)
        at org.apache.logging.log4j.core.LoggerContext.updateLoggers(LoggerContext.java:641)
        at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:547)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:617)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:634)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:229)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:153)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:581)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:567)
        at org.redalert1741.powerup.Robot.<clinit>(Robot.java:9)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:259)
        at edu.wpi.first.wpilibj.RobotBase.main(RobotBase.java:216)

Warning at edu.wpi.first.wpilibj.RobotBase.main(RobotBase.java:224): Robots should not quit, but yours did!
Error at edu.wpi.first.wpilibj.RobotBase.main(RobotBase.java:225): Could not instantiate robot org.redalert1741.powerup.Robot!
```

**Comment by dracco1993** [comment]
I blame @tricktrap

**Comment by randomtestfive** [comment]
[this](https://github.com/apache/logging-log4j2/blob/master/log4j-core/src/main/java/org/apache/logging/log4j/core/LoggerContext.java#L654) is the line that crashes things in log4j2

**Comment by swapnilGitTest** [comment]
any solution on above issue, i am facing same issue
